### ISSUE TITLE
can we use the math.h library in this repository

### ISSUE THREAD

**Issue by oliviaholly** [evanhyd/MeowyPlayer#6]

**Comment by evanhyd** [comment]
Yes! GO has a feature called CGO that can create Go bindings for C libraries and operating system calls. . Such tools are called foreign-function interfaces (FFIs), and CGO is not the only one for Go programs. SWIG (swig.org) is another; it provides more complex features for integrating with C++ classes. As far as I am aware, the Fyne library used in MeowyPlayer uses CGO to call C driver code to render the GUI, which is why MeowyPlayer requires gcc to compile.
